SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 800
SCREEN_UPDATE_RATE = 1 / 60
LOAD_TEXTURES = True
PATH_TEXTURES = './textures/'
SCORE_BOARD_START_X = 350
SCORE_BOARD_START_Y = 350

PLAYER_SCALE = 2
PLAYER_SIZE = PLAYER_SCALE * 20

Cell_SCALE = 3
START_DRAW_X, START_DRAW_Y = -((SCREEN_WIDTH // 2) - 30), ((SCREEN_HEIGHT // 2) - 50)
N_CELLS, M_CELLS = 10, 10
MARGIN = 30

DIE_SCALE = 4
DIE_SIZE = DIE_SCALE * 20
DIE_X, DIE_Y = 350, -350
SEED = -1
